#!/bin/bash

sayi1=18
sayi2=3
toplam=$((sayi1 + sayi2))
echo ’Sayı 1:’ $sayi1
echo ’Sayı 2 :’ $sayi2


echo 'Toplam =' $toplam
fark=$((sayi1 - sayi2))
echo 'Fark =' $fark
carpim=$((sayi1 * sayi2))
echo 'Çarpım =' $carpim
bolum=$((sayi1 / sayi2))
echo 'Bölüm =' $bolum
mod=$((sayi1 % sayi2))
echo 'Mod =' $mod
us=$((sayi1 ** sayi2))
echo 'Üs =' $us
